### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by agaolong** [conis/Purelog#15]
E:\Workspaces\JavaScript\Purelog\purelog>node-dev app.js
TypeError: undefined is not a function
    at Object.<anonymous> (E:\Workspaces\JavaScript\Purelog\purelog\app.js:8:5)
    at Module._compile (module.js:460:26)
    at Module._extensions..js (module.js:478:10)
    at Object.nodeDevHook [as .js](C:UsersAdministratorAppDataRoamingnpmnode_modulesnode-devlibhook.js:43:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\node-dev\lib\wrap.js:58:1)
    at Module._compile (module.js:460:26)

**Comment by wvv8oo** [comment]
应该不支持express 4.x，而package.json没有限制具体的版本，我觉得你可以先把package.json中的express版本改为3.x
即

express: "3.x"

**Comment by ALi-yare-330** [comment]
Hi
